### PR TITLE
Fix #220: create test users using command-line

### LINKED ISSUE #220: Tests do not pass with latest Gitea
https://travis-ci.org/bozaro/git-as-svn/jobs/504687639

    2019-03-11T13:30:50,581  WARN [SvnServer-thread-55] (GiteaUserDB.java:88) - User password check error: testuser
    io.gitea.ApiException: Content type "text/html; charset=UTF-8" is not supported for type: class io.gitea.model.User
    	at io.gitea.ApiClient.deserialize(ApiClient.java:725) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at io.gitea.ApiClient.handleResponse(ApiClient.java:920) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at io.gitea.ApiClient.execute(ApiClient.java:847) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at io.gitea.api.UserApi.userGetCurrentWithHttpInfo(UserApi.java:3375) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at io.gitea.api.UserApi.userGetCurrent(UserApi.java:3362) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at svnserver.ext.gitea.auth.GiteaUserDB.check(GiteaUserDB.java:83) ~[main/:?]
    	at svnserver.auth.PlainAuthenticator.authenticate(PlainAuthenticator.java:47) ~[main/:?]
    	at svnserver.server.SvnServer.authenticate(SvnServer.java:306) ~[main/:?]
    	at svnserver.server.SessionContext.authenticate(SessionContext.java:78) ~[main/:?]
    	at svnserver.server.SvnServer.serveClient(SvnServer.java:197) ~[main/:?]
    	at svnserver.server.SvnServer.lambda$run$1(SvnServer.java:172) ~[main/:?]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
    	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

### PR DESCRIPTION
**Pull request by zeripath**
When creating users by API gitea defaults to force users to change passwords. This PR creates the test
users using the command-line as there is no option currently to switch this off in version <1.8.0.

### CODE REVIEW

File: src/test/java/svnserver/ext/gitea/GiteaIntegrationTest.java [hunk 1]
```diff
@@ -168,16 +168,17 @@ private User createUser(@NotNull String username, @NotNull String password) thro
 
   @NotNull
   private User createUser(@NotNull String username, @NotNull String email, @NotNull String password) throws Exception {
+    // Need to create user using command line because users now default to requiring to change password
+    ExecResult createUserHelpResult = gitea.execInContainer("gitea", "admin", "create-user", "--help", "-c", "/data/gitea/conf/app.ini");
+    boolean mustChangePassword = createUserHelpResult.getStdout().indexOf("--must-change-password") > -1;
+    String mustChangePasswordString = mustChangePassword ? "--must-change-password=false" : "";
+    gitea.execInContainer("gitea", "admin", "create-user", "--name", username,
```
Comment (slonopotamus) [inline src/test/java/svnserver/ext/gitea/GiteaIntegrationTest.java]: I think you want to check exit code here to make sure that command completed successfully.
