### PR TITLE
Fixes #217.

### LINKED ISSUE #217: GiteaIntegrationTest.testGiteaMapping fails with latest Gitea
https://travis-ci.org/bozaro/git-as-svn/jobs/460845508

    java.lang.AssertionError: Expected SVNAuthenticationException to be thrown, but nothing was thrown
        at org.testng.Assert.expectThrows(Assert.java:1394)
        at org.testng.Assert.assertThrows(Assert.java:1364)
        at svnserver.ext.gitea.GiteaIntegrationTest.testGiteaMapping(GiteaIntegrationTest.java:257)

This didn't happen two days ago: https://travis-ci.org/bozaro/git-as-svn/builds/459794680

@zeripath

### PR DESCRIPTION
**Pull request by zeripath**
Throw a FileNotFoundException when trying to read a private repository
anonymously. Fixes #217.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: src/main/java/svnserver/ext/gitea/mapping/GiteaAccess.java [hunk 1]
```diff
@@ -75,6 +75,7 @@ public Repository load(@NotNull String userName) throws Exception {
                   repository.getPermissions().setPush(false);
                   return repository;
                 }
+                throw new FileNotFoundException();
```
Comment (slonopotamus) [inline src/main/java/svnserver/ext/gitea/mapping/GiteaAccess.java]: I don't understand the logic of this code. Doesn't your change mean that anonymous users cannot access any non-private repos?
